name: Build Revanced Apps

on:
  workflow_dispatch:
    inputs:
      apps-to-build:
        description: "Choose the apps to build (comma separated)"
        required: true

jobs:
  get-apps-to-build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          apps="${{ needs.workflow_dispatch.inputs.apps-to-build }}"
          IFS=',' read -ra apps_array <<< "$apps"
          matrix=$(printf ",%s" "${apps_array[@]}")
          matrix=${matrix:1}
          echo "::set-output name=matrix::[$matrix]"

  build-apps:
    name: Build Apps
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        app: ${{needs.get-apps-to-build.outputs.matrix}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java and Python
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build ${{ matrix.app }}
        run: python main.py ${{ matrix.app }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: revanced-${{ matrix.app }}
          path: |
            revanced-cache/output-${{ matrix.app }}_signed.apk
